from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Any

from src.models.mapping_artifact import MappingArtifact, MappingEntry, MappingOrigin


class MappingCompatibilityError(ValueError):
    def __init__(self, category: str, detail: str, remediation: str) -> None:
        self.category = category
        self.detail = detail
        self.remediation = remediation
        super().__init__(f"{category}: {detail}. Remediation: {remediation}")


class CanonicalMappingAdapter:
    supported_schema_versions = {"1.0"}
    supported_mapping_format = "canonical-v1"
    supported_wrapper_contract_versions = {"1.0"}

    _REMEDIATION_HINTS = {
        "unsupported_schema_version": "Re-export mapping with a supported application version.",
        "unknown_engine_id": "Install/enable the backend referenced by this mapping and retry.",
        "missing_required_metadata": "Use a valid canonical mapping artifact with full origin metadata.",
        "unsupported_mapping_format": "Provide a canonical-v1 mapping export generated by this application.",
        "origin_backend_unavailable": "Run readiness checks and restore the origin backend dependencies/models.",
        "invalid_mapping_file": "Verify mapping path and JSON content, then re-export mapping if needed.",
    }

    def _raise(self, category: str, detail: str) -> None:
        remediation = self._REMEDIATION_HINTS.get(category, "Review mapping compatibility requirements.")
        raise MappingCompatibilityError(category=category, detail=detail, remediation=remediation)

    def dump(self, artifact: MappingArtifact, path: Path) -> None:
        artifact.validate()
        payload = asdict(artifact)
        payload["origin"]["generated_at"] = artifact.origin.generated_at.isoformat()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    def _parse_required_metadata(self, raw: dict[str, Any]) -> tuple[str, str, MappingOrigin]:
        schema_version = str(raw.get("schema_version", "")).strip()
        mapping_format = str(raw.get("mapping_format", "")).strip()
        origin_raw = raw.get("origin")

        if not schema_version or not mapping_format or not isinstance(origin_raw, dict):
            self._raise("missing_required_metadata", "schema_version, mapping_format, and origin are required")

        engine_id = str(origin_raw.get("engine_id", "")).strip()
        generated_at_raw = origin_raw.get("generated_at")
        wrapper_contract_version = str(origin_raw.get("wrapper_contract_version", "")).strip()

        if not engine_id:
            self._raise("missing_required_metadata", "origin.engine_id is required")
        if not generated_at_raw:
            self._raise("missing_required_metadata", "origin.generated_at is required")
        if not wrapper_contract_version:
            self._raise("missing_required_metadata", "origin.wrapper_contract_version is required")

        try:
            generated_at = datetime.fromisoformat(str(generated_at_raw))
        except Exception as exc:
            self._raise("missing_required_metadata", f"origin.generated_at must be ISO datetime ({exc})")

        origin = MappingOrigin(
            engine_id=engine_id,
            generated_at=generated_at,
            wrapper_contract_version=wrapper_contract_version,
        )
        return schema_version, mapping_format, origin

    def load(self, path: Path) -> MappingArtifact:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            self._raise("invalid_mapping_file", f"unable to parse mapping file '{path}': {exc}")

        if not isinstance(payload, dict):
            self._raise("invalid_mapping_file", "mapping payload must be a JSON object")

        schema_version, mapping_format, origin = self._parse_required_metadata(payload)

        entries_raw = payload.get("entries", [])
        if not isinstance(entries_raw, list):
            self._raise("invalid_mapping_file", "entries must be a list")

        entries: list[MappingEntry] = []
        for index, item in enumerate(entries_raw):
            if not isinstance(item, dict):
                self._raise("invalid_mapping_file", f"entries[{index}] must be an object")

            placeholder = str(item.get("placeholder", "")).strip()
            original_value = str(item.get("original_value", "")).strip()
            entity_type = str(item.get("entity_type", "")).strip()
            if not placeholder or not original_value or not entity_type:
                self._raise(
                    "invalid_mapping_file",
                    f"entries[{index}] must define placeholder/original_value/entity_type",
                )

            position_ranges_raw = item.get("position_ranges", [])
            if not isinstance(position_ranges_raw, list):
                self._raise("invalid_mapping_file", f"entries[{index}].position_ranges must be a list")

            position_ranges: list[tuple[int, int]] = []
            for r_index, value in enumerate(position_ranges_raw):
                if not isinstance(value, (list, tuple)) or len(value) != 2:
                    self._raise(
                        "invalid_mapping_file",
                        f"entries[{index}].position_ranges[{r_index}] must contain two integers",
                    )
                start, end = value
                if not isinstance(start, int) or not isinstance(end, int):
                    self._raise(
                        "invalid_mapping_file",
                        f"entries[{index}].position_ranges[{r_index}] values must be integers",
                    )
                position_ranges.append((start, end))

            entries.append(
                MappingEntry(
                    placeholder=placeholder,
                    original_value=original_value,
                    entity_type=entity_type,
                    position_ranges=position_ranges,
                )
            )

        artifact = MappingArtifact(
            schema_version=schema_version,
            mapping_format=mapping_format,
            origin=origin,
            entries=entries,
            integrity_hash=payload.get("integrity_hash"),
        )
        self.validate_compatibility(artifact)
        return artifact

    def validate_compatibility(
        self,
        artifact: MappingArtifact,
        supported_engine_ids: set[str] | None = None,
    ) -> None:
        if artifact.schema_version not in self.supported_schema_versions:
            self._raise(
                "unsupported_schema_version",
                f"schema_version '{artifact.schema_version}' is not supported",
            )

        if artifact.mapping_format != self.supported_mapping_format:
            self._raise(
                "unsupported_mapping_format",
                f"mapping_format '{artifact.mapping_format}' must be '{self.supported_mapping_format}'",
            )

        if not artifact.origin.engine_id:
            self._raise("missing_required_metadata", "origin.engine_id is required")

        if artifact.origin.generated_at is None:
            self._raise("missing_required_metadata", "origin.generated_at is required")

        if artifact.origin.wrapper_contract_version not in self.supported_wrapper_contract_versions:
            self._raise(
                "unsupported_schema_version",
                "origin.wrapper_contract_version is not supported",
            )

        if supported_engine_ids is not None and artifact.origin.engine_id not in supported_engine_ids:
            self._raise(
                "unknown_engine_id",
                f"origin.engine_id '{artifact.origin.engine_id}' is not recognized",
            )

    def validate_origin_backend_availability(self, *, engine_id: str, availability_status: str) -> None:
        if availability_status == "unavailable":
            self._raise(
                "origin_backend_unavailable",
                f"backend '{engine_id}' is unavailable for deanonymization",
            )
